### PR TITLE
Fix BackURL redirect with strict or lax session cookie security.

### LINKED ISSUE #45: Session-cookie with samesite = strict breaks login-procedure
In the latest release of Silverstripe CMS (>4.12) the samesite-attribute for cookies is configurable. It is recommended to set this value to `strict` for the cookies and the session-cookie. (see https://docs.silverstripe.org/en/4/changelogs/4.12.0/#cookies-samesite)

I believe this introduces a problem for the SAML-authentication. From what I understand, the problem lies within the session-cookie. This session-cookie should not be loaded, after returning from the IdP (on /saml/asc) - since this is another domain (not samesite). This is roughly same scenario as IdP-initiated logins, where no prior session-cookie is available on the first request.

The problem seems to be specifically in the redirection at the very end of asc() method. Here the user is redirected via 301 to the  desired destinationpage. Because of this same-site cookie restriction, this next page doesn't get the proper session-cookie ans Silverstripe starts a new session.

Let me try explain with some screenshots:

## Scenario lax: 
Same-site set to `lax` (the session-cookie is held correctly)

### /saml/acs
image
_the request cookie is also set, because I was using SP-initiated request. This session is reset by the login process. The session-cookie starts with `k3d...` is send to the next page. The response code of this page is 302._

### /home (destination page)
image
_the same session-cookie is still there, starting with `k3d...`_

## Scenario strict: 
Same-site set to `strict` (the session-cookie is NOT held correctly)

### /saml/acs
image
_the request cookie is empty, since the same site attribute prevents this. No problem, a new session-cookie is set starting with `nqb...` _

### /home (destination page)
image
_the request cookie is empty, because the 302 redirect is treated with the same cookies as the original request. A new session-cookie is set `uk9...` and thus not allowing us the keep the logged in state for this page._

## Reproduce
- Use CMS 3.12
- Set yml with same-site cookies to strict (see https://docs.silverstripe.org/en/4/changelogs/4.12.0/#cookies-samesite)
- Temporary prevent the redirect in the saml/asc flow. For instance by putting a `die('done asc')` in the [`getRedirect()`-method](https://github.com/silverstripe/silverstripe-saml/blob/master/src/Control/SAMLController.php#L250) 
- Open the `/home`  page in a new tab, and see the Member is still logged in correctly

## Solution
The solutions for us was to redirect the user via the browser (meta-refresh), so the destination-page is allowed to use the same session-cookie. Totally not ideal, but works for now. For inspiration see [htmlRedirect](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Control/HTTPResponse.php#L359) in the framework

### PR DESCRIPTION
**Pull request by mateusz**
Should fix https://github.com/silverstripe/silverstripe-saml/issues/45

Needs cross-check, I only tested it on my SAML setup with Google Workspace. 

Also, someone wearing a security hat should see if this is ok.

### CODE REVIEW

File: src/Helpers/SAMLHelper.php [hunk 1]
```diff
@@ -75,7 +75,8 @@ public function redirect(RequestHandler $requestHandler = null, HTTPRequest $req
         $additionalGetQueryParams = $this->getAdditionalGETQueryParameters();
 
         try {
-            $auth->login(Director::absoluteBaseURL() . 'saml/', $additionalGetQueryParams);
```
Comment (mateusz) [inline src/Helpers/SAMLHelper.php:78]: By the way, this usage of login's first parameter is wrong, it results in a URL like `https://mysite.comsaml/`, i.e. it's missing the slash. The bug didn't manifest as an issue, because RelayState isn't used anyway.

**Review by satrun77 — APPROVED** [review]
